version: "3.9"
services:
  magnetico:
    image: "ghcr.io/tgragnato/magnetico:latest"
    container_name: "magnetico"
    restart: unless-stopped
    command: "--database=sqlite3:///data/magnetico.sqlite3 --addr=0.0.0.0:8080"
    volumes:
      - "magnetico-data:/data"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.magnetico.rule=Host(`magnetico.ozeliurs.com`)"
      - "traefik.http.routers.magnetico.entrypoints=websecure"
      - "traefik.http.routers.magnetico.tls.certresolver=letsencrypt"
      - "traefik.http.services.magnetico.loadbalancer.server.port=8080"
      - "traefik.http.routers.magnetico.middlewares=magnetico-auth"
      - "traefik.http.middlewares.magnetico-auth.basicauth.users=admin:$$apr1$$2UdV6.CB$$.abJTJmhd/7fhPIafSSpm0"

networks:
  traefik:
    external: true

volumes:
  magnetico-data:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/appdata/magnetico"
      o: bind
